spring:
  application:
    name: bpe-platform
  
  datasource:
    url: jdbc:mysql://192.168.125.61:3306/BPE_STAGE?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
    username: root
    password: dkfdptmdps404
    driver-class-name: com.mysql.cj.jdbc.Driver
  
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
        format_sql: true
  
  thymeleaf:
    cache: false
    prefix: classpath:/templates/
    suffix: .html
    mode: HTML
    encoding: UTF-8

server:
  port: 8082
  address: 0.0.0.0

app:
  upload:
    dir: uploads/profiles/
  report:
    script:
      path: src/main/resources/monthly-report/getServerStatus.py
    template:
      path: src/main/resources/monthly-report/template/
    output:
      path: src/main/resources/monthly-report/
  elasticsearch:
    host: http://192.168.125.64:9200
    username: elastic
    password: elastic
    chatbot:
      index: bpe_chatbot_faq
  llm:
    server:
      url: http://192.168.125.70:8088
      enabled: true
      timeout: 30000
      max-tokens: 300
      temperature: 0.2

logging:
  level:
    com.bpe.platform: DEBUG
    org.springframework.security: DEBUG

